[theme]
mode = "dark"
builtin = "Tokyo-Night"

[bar]
order = ["main"]

[bar.main]
position = "top"
margin_ends = 0
radius = 0
concave_edge_corners = false
background_opacity = 0.5
shadow = false
widget_spacing = 12
font_weight = 600

start = ["workspaces", "active_window"]
end = ["sysmon", "tray", "notifications",  "network",  "volume","battery", "settings", "session"]

[shell]
lang = "en"

[shell.panel]
transparency_mode = "solid"

control_center_placement = "floating"
open_near_click_control_center = true

wallpaper_placement = "floating"
wallpaper_position = "center"

session_placement = "floating"
session_position = "center"

[system.monitor]
gpu_poll_seconds = 5.0

[widget.sysmon]
show_label = false

[widget.clock]
format = "%d. %b %H:%M"

[widget.workspaces]
display = "none"
hide_when_empty = true

[widget.active_window]
font_weight = 500

[widget.network]
show_label = false

[widget.tray]
drawer = true

[weather]
effects = false

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[backdrop]
enabled        = true
blur_intensity = 0.5    # 0.0 = no blur, 1.0 = maximum blur
tint_intensity = 0.3    # 0.0 = no tint, 1.0 = fully opaque tint

[osd.kinds]
lock_keys = false

[shell.launcher.dmenu.entry.commands]
command = "printf 'DNF Upgrade\tRun dnf upgrade --refresh\n'"
label = "Commands"
prefix = "/cmd"
glyph = "terminal"
global = false
exec = "foot -e bash -lc 'pkexec dnf upgrade --refresh; read -rp \"Press Enter to close...\"'"
